### PR TITLE
feat: version change + api documentation updated

### PR DESCRIPTION
**Pull request by VolodymyrOrlov**
This is, hopefully, the last PR before we release v0.2.0

In this PR: 
 - I increase version to v0.2.0
 - Update API documentation

### CODE REVIEW

**Review by morenol — APPROVED** [review]
lgtm

**Comment by morenol** [comment]
Maybe we should consider to add a changelog

**Review by rabbitrabid — APPROVED** [review]

**Comment by VolodymyrOrlov** [comment]
> Maybe we should consider to add a changelog, what do you think? @VolodymyrOrlov

I plan to compile major changes to a list, similar to https://smartcorelib.org/about.html#release-notes

**Comment by morenol** [comment]
> > Maybe we should consider to add a changelog, what do you think? @VolodymyrOrlov
> 
> I plan to compile major changes to a list, similar to https://smartcorelib.org/about.html#release-notes

Fine, that looks fine I think that we should add a copy of that in this repo.

**Pull request merged**
