### PR TITLE
Make SerDe Optional

### PR DESCRIPTION
**Pull request by ssorc3**
Make the serde dependency optional and add all the cfg flags. See #51

### CODE REVIEW

**Review by morenol — CHANGES_REQUESTED** [review]
Hi @ssorc3 thanks for your contribution, It looks fine.

I think that we also should add  `#[cfg(feature = "serde")]`  in the tests where serde is being used.

Also, in the test mod of src/algorithm/neighbour/cover_tree.rs and src/algorithm/neighbour/linear_search.rs we need to add the changes for the SimpleDistance struct

**Review by morenol — APPROVED** [review]

**Comment by morenol** [comment]
There is a problem with the CI configuration, but I ran tests in my fork and they worked fine: https://app.circleci.com/pipelines/github/morenol/smartcore?branch=lmm%2Fserde

@VolodymyrOrlov I think that we should modify  .circleci/config.yml to run the tests with --all-features

**Comment by VolodymyrOrlov** [comment]
Hi @ssorc3! Thank you for taking care of #51! Me and @morenol are trying to figure out why Circle CI build was not triggered for your PR and one possible explanation is that [you are following the project fork with your personal account rather than the project itself on CircleCI](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-).

Could you please go by this link https://app.circleci.com/settings/project/github/ssorc3/smartcore

and unfollow the Smartcore project in Circle CI?

**Comment by VolodymyrOrlov** [comment]
> There is a problem with the CI configuration, but I ran tests in my fork and they worked fine: https://app.circleci.com/pipelines/github/morenol/smartcore?branch=lmm%2Fserde
> 
> @VolodymyrOrlov I think that we should modify .circleci/config.yml to run the tests with --all-features

I agree, @ssorc3 could you please replace

```
--features "nalgebra-bindings ndarray-bindings"
``` 

with 

```
--all-features
```

in these 2 lines of config.yml:

https://github.com/smartcorelib/smartcore/blob/development/.circleci/config.yml#L26
https://github.com/smartcorelib/smartcore/blob/development/.circleci/config.yml#L29

**Comment by ssorc3** [comment]
Hi. Just made that change to the circleCI config. I'm not following the project so I don't think that's the issue. Let me know if there's anything else I can do to help with it.

**Review by morenol — APPROVED** [review]

**Review by VolodymyrOrlov — APPROVED** [review]
LGTM, thanks, @ssorc3 !

**Pull request merged**
