### PR TITLE
Move CI to github actions

### PR DESCRIPTION
**Pull request by morenol**
I ran the tests without the PR that I already merged and they failed  in the tests with 32 bits architectures and then with that change they seems to be working fine.

This is done in order to check the compatibility with other architectures and OS in the CI (wasm, windows x86_64, windows i686 , macos, linux x86_64, linux i686).

Note that for the i686 architectures and wasm we are only checking that the library builds without problem and not running the tests.

### CODE REVIEW

**Comment by VolodymyrOrlov** [comment]
Thanks, @morenol! Should I turn CircleCI off?

**Comment by morenol** [comment]
> Thanks, @morenol! Should I turn CircleCI off?

I am not sure tbh

**Comment by VolodymyrOrlov** [comment]
I've just turned it off. Do you know how to trigger re-build by any chance?

**Review by VolodymyrOrlov — DISMISSED** [review]

**Comment by VolodymyrOrlov** [comment]
Can you make some small change to the PR to re-build? I want to make sure CircleCI is not triggered

**Comment by morenol** [comment]
> I've just turned it off. Do you know how to trigger re-build by any chance?

We can re-build them in the actions tab. But I will squash the commits in order to see if the circleci check are removed.

**Comment by morenol** [comment]
@VolodymyrOrlov The thing that you disabled, removed the failing test. But there is still a check of circleci there waiting for execution. I hope that this will disappear for future PRs once the .circleci/config.yml is removed from the development branch

**Comment by VolodymyrOrlov** [comment]
> @VolodymyrOrlov The thing that you disabled, removed the failing test. But there is still a check of circleci there waiting for execution. I hope that this will disappear for future PRs once the .circleci/config.yml is removed from the development branch

I agree, let's merge this PR once it is ready. Once the PR is merged I will create another to verify that CircleCI build is not triggered

**Review by VolodymyrOrlov — APPROVED** [review]

**Pull request merged**
