### PR TITLE
Handle kernel serialization

### LINKED ISSUE #221: Deserialization for Kernel
`Kernel` is now an object-safe trait so we can use its type as `&dyn Kernel`, it has also a `name()` function to have a string representation of the kernel as `LinearKernel`, `RBFKernel`, ...

We would like to provide a functionality that instantiate the kernel's default from a string:
```
"LinearKernel" -> LinearKernel::Default()
```
via a enum
```
pub enum KernelName {
    Linear(LinearKernel),
   ...
}
```
This possibility is known to be not possible in vanilla Rust but there is a library that provides it, see [blogpost](https://fdeantoni.medium.com/rust-and-dynamically-loading-structs-c311d8edbef6).

This feature should be only available and loaded in pairing with the "serde" feature so to avoid adding another library to the deps.

This will allow parameters that contain `pub kernel: Option<&'a dyn Kernel<'a>>,` to be deserializable.

### PR DESCRIPTION
**Pull request by morenol**
Fixes https://github.com/smartcorelib/smartcore/issues/221

### Checklist
- [ ] My branch is up-to-date with development branch.
- [ ] Everything works and tested on latest stable Rust.
- [ ] Coverage and Linting have been applied

### CODE REVIEW

**Comment by morenol** [comment]
Wow, typetag is not usable in wasm, I disabled that for WASM32 target. So we have full serialization/deserialization support in all targets except WASM

**Comment by Mec-iS** [comment]
that is why I wanted default to be empty feature:
`default = []`
 so that it could compiled to Wasm, we can assume that for in-browser application serialisation is not needed in the Wasm binary.

please add some tests for Kernel serialisation/deserialisation

**Comment by morenol** [comment]
> that is why I wanted default to be empty feature: `default = []` so that it could compiled to Wasm, we can assume that for in-browser application serialisation is not needed in the Wasm binary.
> 
> please add some tests for Kernel serialisation/deserialisation

Addressed.

I agree. I think that by default we should not enable any feature

**Comment by morenol** [comment]
> so that it could compiled to Wasm, we can assume that for in-browser application serialisation is not needed in the Wasm binary.

I think that there could be a couple of use cases in wasm where deserialization could be useful, but I think that is ok for now to partially support WASM

**Comment by Mec-iS** [comment]
> I think that there could be a couple of use cases in wasm where deserialization could be useful, but I think that is ok for now to partially support WASM

yes something we can add later or leave it to the implementation in JS

**Comment by Mec-iS** [comment]
@morenol please double check that these changes are inline with the new features setup.

**Review by Mec-iS — APPROVED** [review]

**Pull request merged**
