### PR TITLE
Implement GaussianNB

### PR DESCRIPTION
**Pull request by morenol**
Implementation of a Gaussian Naive bayes classifiers similar to https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.CategoricalNB.html#sklearn.naive_bayes.GaussianNB

### CODE REVIEW

**Comment by VolodymyrOrlov** [comment]
@morenol is this PR ready for review? I ask because it is still marked as draft.

**Comment by morenol** [comment]
Not yet @VolodymyrOrlov, I think that it works but currently there is an excessive amount of cloning that I want to remove

**Comment by VolodymyrOrlov** [comment]
Can you also compare your coefficients with Scikit's Gaussian NB like we did for Categorical NB? https://scikit-learn.org/stable/modules/naive_bayes.html#gaussian-naive-bayes. It would be great if you can add a unit test that compares coefficients directly. Comparing `y_hat` with `y` might not be precise enough.

**Review by VolodymyrOrlov — APPROVED** [review]
lgtm

**Pull request merged**
