### PR TITLE
In Naive Bayes, avoid using `Option::unwrap` and so avoid panicking from NaN values

### LINKED ISSUE #273: Panics in NaiveBayes
# I'm submitting a 
- [X] bug report.
- [X] improvement.
- [ ] feature request.

# Current Behaviour:
There are unresolved cases of panicking in the function `naive_bayes::BaseNaiveBayes::predict` by unwraping `Option`

# Expected Behaviour:
These cases can be resolved.

# Steps to reproduce:
Introducing NaNs in data

# Environment:
Version 0.3.2 of Smartcore

# Do you want to work on this issue?
yes

# Suggestions
These cases of panic in function `naive_bayes::BaseNaiveBayes::predict` can be resolved by compromission for tricky values:
- Nan at line 109:
```rust
.max_by(|(_, p1), (_, p2)| p1.partial_cmp(p2).unwrap())
```
- Unpredictible cases can return a `Failed` error instead of unwraping at line 110

### PR DESCRIPTION
**Pull request by corebreaker**
Fixes #273 

### Checklist
- [X] My branch is up-to-date with development branch.
- [X] Everything works and tested on latest stable Rust.
- [X] Coverage and Linting have been applied 

### Current behaviour
Panics in function `naive_bayes::BaseNaiveBayes::predict`

### New expected behaviour
No panics with NaNs

### CODE REVIEW

**Comment by morenol** [comment]
Thanks @corebreaker, can you add an unit test for that?

**Comment by corebreaker** [comment]
Sure, @morenol, i'll add an unit test.

**Comment by corebreaker** [comment]
@morenol , unit tests were added.

**Comment by corebreaker** [comment]
Sorry i forgot, review process.

**Review by morenol — APPROVED** [review]
LGTM!

**Pull request merged**
